### ISSUE TITLE
npm run build报错，望指导！

### ISSUE THREAD

**Issue by puterkey** [Xhofe/alist-web#162]
✓ 51 modules transformed.
x Build failed in 1.20s
error during build:
Error: [commonjs--resolver] Missing "./lib" specifier in "solid-icons" package
    at e (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:47581:25)
    at n (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:47581:627)
    at o (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:47581:1297)
    at resolveExportsOrImports (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:48271:20)
    at resolveDeepImport (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:48290:31)
    at tryNodeResolve (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:48015:20)
    at Object.resolveId (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:47765:28)
    at file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:19563:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:19463:28)
    at async resolveId (file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:18144:26)
    at async ModuleLoader.resolveId (file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:18547:15)
    at async Object.resolveId (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:8237:10)
    at async PluginDriver.hookFirstAndGetPlugin (file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:19463:28)
    at async resolveId (file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:18144:26)
    at async ModuleLoader.resolveId (file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:18547:15)
    at async file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:18851:50

**Comment by Luminet2023** [comment]
> ✓ 51 modules transformed. x Build failed in 1.20s error during build: Error: [commonjs--resolver] Missing "./lib" specifier in "solid-icons" package at e (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:47581:25) at n (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:47581:627) at o (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:47581:1297) at resolveExportsOrImports (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:48271:20) at resolveDeepImport (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:48290:31) at tryNodeResolve (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:48015:20) at Object.resolveId (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:47765:28) at file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:19563:40 at async PluginDriver.hookFirstAndGetPlugin (file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:19463:28) at async resolveId (file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:18144:26) at async ModuleLoader.resolveId (file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:18547:15) at async Object.resolveId (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:8237:10) at async PluginDriver.hookFirstAndGetPlugin (file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:19463:28) at async resolveId (file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:18144:26) at async ModuleLoader.resolveId (file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:18547:15) at async file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:18851:50

用npm有问题，得用pnpm编译

**Comment by gg22mm** [comment]
> > ✓ 51 modules transformed. x Build failed in 1.20s error during build: Error: [commonjs--resolver] Missing "./lib" specifier in "solid-icons" package at e (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:47581:25) at n (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:47581:627) at o (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:47581:1297) at resolveExportsOrImports (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:48271:20) at resolveDeepImport (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:48290:31) at tryNodeResolve (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:48015:20) at Object.resolveId (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:47765:28) at file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:19563:40 at async PluginDriver.hookFirstAndGetPlugin (file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:19463:28) at async resolveId (file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:18144:26) at async ModuleLoader.resolveId (file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:18547:15) at async Object.resolveId (file:///D:/Sam/FamilyApp/alist/web/node_modules/vite/dist/node/chunks/dep-B-u6xNiR.js:8237:10) at async PluginDriver.hookFirstAndGetPlugin (file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:19463:28) at async resolveId (file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:18144:26) at async ModuleLoader.resolveId (file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:18547:15) at async file:///D:/Sam/FamilyApp/alist/web/node_modules/rollup/dist/es/shared/node-entry.js:18851:50
> 
> 用npm有问题，得用pnpm编译

pnpm   It's the same problem  / pnpm  也是一样的问题
